-- This is an empty migration.

ALTER TABLE "User" ALTER COLUMN "username" TYPE VARCHAR(55);

ALTER TABLE "User" ALTER COLUMN "email" TYPE VARCHAR(55);

ALTER TABLE "User" ALTER COLUMN "firebaseId" TYPE VARCHAR(128);

ALTER TABLE "Renter" ALTER COLUMN "name" TYPE VARCHAR(55);

ALTER TABLE "Renter" ALTER COLUMN "email" TYPE VARCHAR(55);

ALTER TABLE "Renter" ALTER COLUMN "address" TYPE VARCHAR(128);

ALTER TABLE "Renter" ALTER COLUMN "phoneNumber" TYPE VARCHAR(15);

ALTER TABLE "Landlord" ALTER COLUMN "name" TYPE VARCHAR(55);

ALTER TABLE "Landlord" ALTER COLUMN "email" TYPE VARCHAR(55);

ALTER TABLE "Landlord" ALTER COLUMN "address" TYPE VARCHAR(128);

ALTER TABLE "Landlord" ALTER COLUMN "phoneNumber" TYPE VARCHAR(15);

ALTER TABLE "Property" ALTER COLUMN "name" TYPE VARCHAR(55);

ALTER TABLE "Property" ALTER COLUMN "address" TYPE VARCHAR(128);

ALTER TABLE "Unit" ALTER COLUMN "name" TYPE VARCHAR(10);

ALTER TABLE "Announcement" ALTER COLUMN "title" TYPE VARCHAR(55);

ALTER TABLE "Announcement" ALTER COLUMN "body" TYPE VARCHAR(255);

ALTER TABLE "Unit" ADD CONSTRAINT "payPeriod" CHECK ("payPeriod" > 0);